POST http://localhost:3001/api/users
content-type: application/json

{
    "blogs": [],
    "username": "SHR3NT",
    "name": "Superuser",
    "password": "password"
}

###
GET http://localhost:3001/api/users